# Generated by Django 4.2 on 2023-07-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.announcement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
