# Generated by Django 4.2 on 2023-07-08 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_alter_response_response_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_post', to='board.announcement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
