# Generated by Django 4.2 on 2023-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_response_response_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
