# Generated by Django 4.2 on 2023-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_announcement_title_announcement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categoryType',
            field=models.CharField(choices=[('tanks', 'Танки'), ('heals', 'Хилы'), ('damage_dealers', 'Дамагеры'), ('merchants', 'Торговецы'), ('guildmasters', 'Гилдмастеры'), ('questgivers', 'Квестгиверы'), ('smiths', 'Кузнецы'), ('tanners', 'Кожевникы'), ('potions_masters', 'Зельевары'), ('spell_masters', 'Мастера заклинаний')], default='tanks', max_length=15),
        ),
    ]
